// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // "Guías" navbar tab: recuperación después de apagones (docking/laptop).
  // Categorías declaradas explícitamente (en vez de dirName: '.') para que
  // no incluyan docs/seguridad, que tiene su propia pestaña/sidebar abajo.
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Docking',
      items: [{type: 'autogenerated', dirName: 'docking'}],
    },
    {
      type: 'category',
      label: 'Laptop',
      items: [{type: 'autogenerated', dirName: 'laptop'}],
    },
  ],

  // "Seguridad" navbar tab: phishing y otros temas de seguridad.
  seguridadSidebar: [
    {
      type: 'category',
      label: 'Seguridad',
      link: {
        type: 'generated-index',
        slug: '/seguridad',
        description:
          'Guías de seguridad: cómo reconocer phishing y otros temas de acceso seguro.',
      },
      items: [{type: 'autogenerated', dirName: 'seguridad'}],
    },
  ],
};

export default sidebars;
